spring:
  application:
    name: Quote-Provider-Bot
  security:
    oauth2:
      client:
        registration:
          reddit:
            clientId:
            clientSecret:

authorsPath: src/main/resources/AuthorsQuotes
botName: QuotesProviderBot
redditUrl: www.reddit.com
