spring:
  application:
    name: Quote-Manager
  datasource:
    initialization-mode: always
    url: jdbc:mysql://localhost:3308/quotemanager
    username: root
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: none
      dialect: org.hibernate.dialect.MySQL8Dialect
      naming:
        physical-strategy: com.crommvardek.quotemanager.config.UpperCaseNamingStrategy
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
    com:
      zaxxer:
        hikari:
          HikariConfig: DEBUG