spring:
  application:
    name: Quote-Provider-Bot
  security:
    oauth2:
      client:
        registration:
          reddit:
            clientId:
            clientSecret:
  datasource:
    url:
    username: admin
    password: admin
    driver-class-name:
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: none