spring:
  application:
    name: Quote-Provider-Bot
  security:
    oauth2:
      client:
        registration:
          reddit:
            clientId:
            clientSecret:
  datasource:
    initialization-mode: always
    url: jdbc:mysql://localhost:3308/quotemanager
    username: root
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: none