DROP TABLE IF EXISTS AUTHOR;
DROP TABLE IF EXISTS QUOTE;

CREATE TABLE AUTHOR (
    ID INT AUTO-INCREMENT PRIMARY KEY,
    AUTHOR_NAME varchar(250) NOT NULL
)

CREATE TABLE QUOTE (
    ID INT AUTO-INCREMENT PRIMARY KEY,
    QUOTE_TEXT varchar(21844) CHARACTER SET utf8 NOT NULL,
    AUTHOR_ID INT,
    FOREIGN KEY (AUTHOR_ID)
        REFERENCES AUTHOR(ID)
        ON DELETE CASCADE
)