DROP TABLE IF EXISTS QUOTE;

DROP TABLE IF EXISTS AUTHOR;

CREATE TABLE AUTHOR (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    AUTHOR_NAME VARCHAR(250) NOT NULL
);

CREATE TABLE QUOTE (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    QUOTE_TEXT VARCHAR(10000) CHARACTER SET utf8 NOT NULL,
    AUTHOR_ID INT NOT NULL,
    FOREIGN KEY (AUTHOR_ID)
        REFERENCES AUTHOR (ID)
        ON DELETE CASCADE
);

COMMIT;