version: '3'

services:

  quote-manager-mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: quotemanager
    cap_add:
      - SYS_NICE
    ports:
      - "3308:3306"