version: '3'

services:

  quote-manager-db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./data:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: quotemanager
    cap_add:
      - SYS_NICE
    ports:
      - "3308:3306"